ridgeback_ur5:
  motors_name:
    - front_left_wheel
    - front_right_wheel
    - rear_left_wheel
    - rear_right_wheel
    - ur_arm_shoulder_pan_joint
    - ur_arm_shoulder_lift_joint
    - ur_arm_elbow_joint
    - ur_arm_wrist_1_joint
    - ur_arm_wrist_2_joint
    - ur_arm_wrist_3_joint
  pos_sensor_name:
    - front_left_wheel_sensor
    - front_right_wheel_sensor
    - rear_left_wheel_sensor
    - rear_right_wheel_sensor
    - ur_arm_shoulder_pan_joint_sensor
    - ur_arm_shoulder_lift_joint_sensor
    - ur_arm_elbow_joint_sensor
    - ur_arm_wrist_1_joint_sensor
    - ur_arm_wrist_2_joint_sensor
    - ur_arm_wrist_3_joint_sensor