obstacles:
  enabled: false
  constraint_type: hard

  # extra margin between objects
  # Important: this needs to be > 0 for the resulting constraint to be
  # differentiable
  minimum_distance: 0.1

  # relaxed barrier function parameters
  mu: 1e-2
  delta: 1e-3


objects:
  # EE is a special object
  # wood tray
  ee:
    shape: cuboid
    side_lengths: [0.285, 0.285, 0.02]
    position: [0, 0, -0.01]  # box centroid relative to r_ew_w

  cube:
    mass: 1.0
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.01]

  bottle:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape: cylinder
    radius: 0.0325
    height: 0.15

arrangements:
  nothing:
    objects: []

  pink_bottle:
    objects:
      -
        name: bottle
        type: pink_bottle
        parent: ee
        offset:
          x: 0.035
          y: -0.035
    contacts:
      -
        first: ee
        second: bottle
        mu: 0.26
        mu_margin: 0.026
        support_area_inset: 0.005