objects:
  cube:
    body:
#      com: could be express by com_offset(offset of shape's centroid
      com_offset : [ 0., 0., 0.]
      side_lengths: [ 0., 0., 0.] #to express the shape
      mass: 1.0
      shape: cuboid
#      inertia: could be computer if the shape is  cuboid | cylinder | wedge
#    support_area: could be computer if the shape is  cuboid | cylinder | wedge
    mu:
#    r_tau:
#    com_height:

contacts:
  -
    first:
    second:
    mu:
    mu_margin:
    support_area_inset: