controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  upright_controller:
    type: ddt/UprightController
    init_pos:
      x: 0.05
      y: 0.0
      z: 0.42