controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  upright_controller:
    type: ddt/UprightController
    init_pos:
      x: 0.2
      y: 0.0
      z: 0.7
    arm_urdf: /home/lsy/upright_ws/src/upright_asset/description/urdf/manipulator/robot.urdf
