motors_name:
  - left_j3
  - right_j3
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6
pos_sensor_name:
  - left_j3_sensor
  - right_j3_sensor
  - joint1_sensor
  - joint2_sensor
  - joint3_sensor
  - joint4_sensor
  - joint5_sensor
  - joint6_sensor